import { useRef, useState } from 'react';
import { Button, DialogOverlay } from '../components/ui';
import { cx } from '../components/ui-utils';
import { finalizeImport, isDisplayNameTaken, prepareImport } from '../lib/importBank';
import type { PreparedImport } from '../lib/importBank';

// Add-module flow: pick a file → validate → (dedup) name the module with a live
// availability check → install. Display names are enforced unique; the internal
// id is generated by installBank.
export function ImportDialog({ onClose, onInstalled }: { onClose: () => void; onInstalled: (id: string) => void }) {
  const fileRef = useRef<HTMLInputElement>(null);
  const [busy, setBusy] = useState(false);
  const [errors, setErrors] = useState<string[]>([]);
  const [prepared, setPrepared] = useState<PreparedImport | null>(null);
  const [name, setName] = useState('');

  async function onFile(file: File) {
    setBusy(true);
    setErrors([]);
    const r = await prepareImport(file);
    setBusy(false);
    if (!r.ok) { setErrors(r.errors); return; }
    setPrepared(r);
    setName(r.suggestedName);
  }

  const trimmed = name.trim();
  const taken = prepared ? isDisplayNameTaken(trimmed, prepared.metas) : false;
  const nameOk = trimmed.length > 0 && !taken;

  async function install() {
    if (!prepared || !nameOk) return;
    setBusy(true);
    try {
      const id = await finalizeImport(prepared.validated, trimmed);
      onInstalled(id);
    } catch (e) {
      setErrors([e instanceof Error ? e.message : 'could not install the bank']);
      setBusy(false);
    }
  }

  return (
    <DialogOverlay onClose={onClose} label="Add module">
      <h3 className="text-base font-semibold tracking-tight text-fg">Add a module</h3>

      {!prepared ? (
        <>
          <p className="mt-1.5 text-sm text-muted">Import a .zip or .json question bank from your device.</p>
          <div className="mt-4">
            <Button variant="primary" disabled={busy} onClick={() => fileRef.current?.click()}>
              {busy ? 'Reading…' : 'Choose file'}
            </Button>
            <input
              ref={fileRef}
              type="file"
              accept=".zip,.json,application/json,application/zip"
              className="hidden"
              onChange={(e) => { const f = e.target.files?.[0]; e.target.value = ''; if (f) void onFile(f); }}
            />
          </div>
        </>
      ) : (
        <>
          <label className="mt-4 block text-sm font-medium text-muted">
            Module name
            <input
              autoFocus
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="mt-1.5 w-full rounded-xl border border-line bg-surface px-3.5 py-2.5 text-fg transition focus:border-line-strong"
            />
          </label>
          <p className={cx('mt-1.5 text-xs', trimmed.length === 0 ? 'text-faint' : taken ? 'text-bad' : 'text-good')}>
            {trimmed.length === 0 ? 'Enter a name' : taken ? 'This name is already in use' : 'Name is available'}
          </p>
          {prepared.sourceExists && (
            <p className="mt-2 rounded-lg bg-surface-2 px-3 py-2 text-xs text-muted">
              Installs a separate copy. Merging updates into an existing module comes later.
            </p>
          )}
        </>
      )}

      {errors.length > 0 && (
        <ul className="mt-3 max-h-40 list-disc space-y-1 overflow-auto pl-4 text-xs text-bad">
          {errors.slice(0, 8).map((e, i) => <li key={i}>{e}</li>)}
          {errors.length > 8 && <li>…and {errors.length - 8} more</li>}
        </ul>
      )}

      <div className="mt-5 flex gap-2">
        <Button className="flex-1" onClick={onClose}>Cancel</Button>
        {prepared && (
          <Button variant="primary" className="flex-1" disabled={!nameOk || busy} onClick={install}>
            {busy ? 'Installing…' : 'Install'}
          </Button>
        )}
      </div>
    </DialogOverlay>
  );
}
